      SUBROUTINE DAY(IPARAM)

C     "REQUIRED TWO DIGIT INTEGER DAY HASN'T BEEN TYPED"
      INTEGER ATEMPT
      COMMON ATEMPT
      ATEMPT = ATEMPT + 1
      WRITE (6,1)

      RETURN

    1 FORMAT (1H ,8HERROR - 
     &24HTHE DATE MUST CONSIST OF, 27H A TWO DIGIT INTEGER NUMBER/
     &1H ,23HFOLLOWED BY A SPACE AND, 21H A THREE LETTER MONTH/
     &1H ,13HPLEASE RETYPE)

      END
