      SUBROUTINE DIGITS(IPARAM)

C     "REQUIRED INTEGER NUMBER HASN'T BEEN INPUT"
      INTEGER ATEMPT
      COMMON ATEMPT
      ATEMPT = ATEMPT + 1
      WRITE (1,3)

      RETURN

    3 FORMAT (1H ,8HERROR - ,30HTHIS MUST BE AN INTEGER NUMBER/
     &1H ,13HPLEASE RETYPE)

      END