      SUBROUTINE FLOAT(IPARAM)

C     "REQUIRED FLOATING POINT NUMBER HASN'T BEEN TYPED"
      INTEGER ATEMPT
      COMMON ATEMPT
      ATEMPT = ATEMPT + 1
      WRITE (1,3)

      RETURN

    3 FORMAT (1H ,8HERROR   36HTHIS MUST BE A FLOATING POINT NUMBER/
     &1H ,13HPLEASE RETYPE)

      END
