      PROGRAM ORIGIN
      
C     PROGRAM WK19 01
C     "INITIALISE ARRAYS AND SPECIALS VARIABLES"

      DIMENSION BANKYR(2)
      DATA BANKYR(1),BANKYR(2)/4HZZZZ,4HZZZZ/

      CALL USERCHECK

C     "WRITE TERMINATOR TO MASTER FILE"
      WRITE (2,1) BANKYR

      STOP

    1 FORMAT (1H ,2A4)

      END
