      PROGRAM SETUP

C     ASHMOLE SCHOOL PROJECT
C     PROGRAM WK19 02

C     "INITIALISE ARRAYS AND SPECIAL VARIABLES"
      EXTERNAL FLOAT, DAY
      INTEGER ATEMPT
      COMMON ATEMPT

      DIMENSION BANKYR(2), BRNAME (3), ANAME(7),
     &BALMTH(3), TRANMH(3), TRANDE(7)
      DIMENSION EOF (2)
      DATA EOF(1),EOF(2)/4HZZZZ,4HZZZZ/

      INTEGER CODENO, SHEETN, BALDT, TRANDT
      LAST = 0

C     "CHECK THE USER"
      CALL USERCHECK

C     "VALID USER"
      WRITE (6,1)

C     "GO TO END OF FILE AND COPY RECORDS TO NEW FILE"
   10 READ (4,2) BANKYR

C     "CHECK FOR END OF READ FILE"
      DO 80 N=1,2
      I = 4
      CALL COMP(I,BANKYR(N),1,EOF(N),1)
      IF(I.NE.4) GO TO 81
   80 CONTINUE
      GO TO 11

C     "COPY A CUSTOMER RECORD"
   81 WRITE (2,82) BANKYR
      READ (4,83) BRNAME, ANAME, CODENO, SHEETN, BALFWD, BALDT, BALMTH
      LAST = CODENO
      WRITE (2,84) BRNAME, ANAME, CODENO, SHEETN, BALFWD, BALDT, BALMTH
    8 READ (4,5) TRANDT
      IF (TRANDT.EQ.99) GO TO 9
      WRITE (2,85) TRANDT
      READ (4,6) TRANMH, TRANDE, DEBS, CREDS
      WRITE (2,7) TRANMH, TRANDE, DEBS, CREDS
      GO TO 8
    9 WRITE (2,85) TRANDT
      GO TO 10

C     "END OF READ FILE REACHED, REQUEST DETAILS FOR NEW CUSTOMER RECORD"
   11 WRITE (6,87)
      WRITE (6,12)

C     "READ BANK YEAR AND VALIDATE"
  501 READ (5,13) BANKYR
      DO 502 JFIELD=1,2
      CALL YEARCHECK (BANKYR(JFIELD), IRESLT)
      IF (IRESLT.EQ.0) GO TO 501
  502 CONTINUE
      WRITE (6,14)

C     "READ BANK NAME AND VALIDATE"
  503 READ (5,15) BRNAME

      DO 504 JFIELD=1,3
      CALL FOURCHECK (BRNAME(JFIELD), IRESLT)
      IF (IRESLT.EQ.0) GO TO 503
  504 CONTINUE
      WRITE (6,16)

C     "READ CUSTOMER NAME AND VALIDATE"
  505 READ (5,17) ANAME

      DO 506 JFIELD=1,7
      CALL FOURCHECK (ANAME ( JFIELD), IRESLT)
      IF(IRESLT.EQ.0) GO TO 505
  506 CONTINUE
  
C     "GIVE VALUES TO CODENUMBER AND SHEET NUMBER"
      CODENO = LAST + 1
      LAST = CODENO
      SHEETN = 1
      WRITE (6,20)

C     "READ AND VALIDATE BALANCE FORWARD"
  510 ATEMPT = 0
      CALL FTRAP(FLOAT)
      READ (5,21) BALFWD
      CALL FRESET
      IF(ATEMPT.GT.0) GO TO 510
      WRITE (6,23)
   53 WRITE (6,50)

C     "READ AND VALIDATE DATE OF DEPOSIT"
  507 ATEMPT = 0
      CALL FTRAP(DAY)
      READ (5,24) BALDT, BALMTH
      CALL FRESET
      IF(ATEMPT.GT.0) GO TO 507
      CALL DATECHECK(BALDT,BALMTH, JFLAG)
      IF(JFLAG.NE.0) GO TO 51
      GO TO 507

C     "PUT NEW CUSTOMER RECORD ON FILE"
   51 WRITE (2,82) BANKYR
      WRITE (2,84) BRNAME, ANAME, CODENO, SHEETN, BALFWD, BALDT, BALMTH
      TRANDT = 99
      WRITE (2,85) TRANDT

C     "ANY MORE CUSTOMER RECORDS TO ADD?"
      WRITE (6,88)
   89 READ (5,90) ANS
      CALL FOURCHECK(ANS, IRESLT)
      IF(IRESLT.EQ.0) GO TO 89
      I = 4
      CALL COMP (I,ANS,1,4HYES , 1)
      IF(I.EQ.4) GO TO 11
      I = 4
      CALL COMP(I,ANS,1,4HNO  , 1)
      IF(I.EQ.4) GO TO 92
      WRITE (6,93)
      GO TO 89

C     "REPLACE TERMINATOR"
   92 WRITE (2,82) EOF

      STOP

    1 FORMAT (1H /1H /1H ,18HRECORD SET UP MODE)
    2 FORMAT (2A4)
    5 FORMAT (I2)
    6 FORMAT (3A1,7A4,2F10.0)
    7 FORMAT (1H ,3A1,7A4,2F10.2)
   12 FORMAT (1H ,29HPLEASE TYPE PRESENT BANK YEAR)
   13 FORMAT (2A4)
   14 FORMAT (1H ,28HPLEASE TYPE BANK BRANCH NAME)
   15 FORMAT (3A4)
   16 FORMAT (1H ,22HPLEASE TYPE CUSTOMER'S,10H FULL NAME)
   17 FORMAT (7A4)
   20 FORMAT (1H ,27HPLEASE TYPE ORIGINAL AMOUNT,16H TO BE DEPOSITED)
   21 FORMAT (F11.0)
   23 FORMAT (1H ,27HPLEASE TYPE DATE OF DEPOSIT)
   24 FORMAT (I2,1X,3A1)
   50 FORMAT (1H , 39HAS TWO DIGITS A SPACE AND THREE LETTERS)
   82 FORMAT (1H ,2A4)
   83 FORMAT (3A4,7A4,I10,I4,F11.0,I2,3A1)
   84 FORMAT (1H ,3A4,7A4,I10,I4,F11.2,I2,3A1)
   85 FORMAT (1H ,I2)
   87 FORMAT (1H /1H ,20HNEW CUSTOMER DETAILS/1H )
   88 FORMAT (1H /1H ,30HIS THERE ANOTHER NEW CUSTOMER?,
     &19H (ANSWER YES OR NO))
   90 FORMAT (A4)
   93 FORMAT (1H ,40HINCORRECT ANSWER - PLEASE TYPE YES OR NO)

      END
